export const storageClasses = {
  STANDARD: "STANDARD",
  REDUCED_REDUNDANCY: "REDUCED_REDUNDANCY",
  STANDARD_IA: "STANDARD_IA",
  ONEZONE_IA: "ONEZONE_IA",
  INTELLIGENT_TIERING: "INTELLIGENT_TIERING",
  GLACIER: "GLACIER",
  DEEP_ARCHIVE: "DEEP_ARCHIVE",
  OUTPOSTS: "OUTPOSTS",
  GLACIER_IR: "GLACIER_IR",
}